name: Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers when you push a tag like v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Web
        run: npx expo export --platform web

      - name: Package Web Build
        run: zip -r web-build.zip dist

      - name: GH Release
        uses: softprops/action-gh-release@v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this version
            - Manual release based on tag ${{ github.ref_name }}
            - (Add manual notes here or use generate_release_notes)
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            web-build.zip
